"""
This file is just the boot method to load some stuff
Do not edit this file, it could break pullit
"""
from ruamel import yaml

# Load our environment
config = yaml.safe_load(open('./config.yml'))
